ansible-collections/community.routeros

- README.md
- plugins/modules/api.py
- plugins/modules/command.py
- plugins/modules/facts.py
Improves documentation on collection usage.
Also I didn't correctly adjust the examples in the modules, they were still using community.network instead of community.routeros.
README.md
plugins/modules/api.py
plugins/modules/command.py
plugins/modules/facts.py
> Improve docs

- plugins/modules/api.py
- plugins/modules/command.py
While looking at the regenerated docs (https://ansible.fontein.de/collections/community/routeros/index.html) I found some more things to improve.
api
command
> More docs updates

- plugins/module_utils/routeros.py
Substitute to_text for to_native as:
https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#raising-errors
lack of compatibility of to_text module
> Change to_text for to_native

- plugins/modules/api.py
Fallout of ansible/ansible#72699.
api
> Fix bool default value.

- plugins/cliconf/routeros.py
Prepare for ansible/ansible#71795
collection
> <plugin_type>: -> name: for plugins

- .github/workflows/ansible-test.yml
- .github/workflows/extra-tests.yml
- .github/workflows/import-galaxy.yml
(cherry picked from commit 7b3900fd6e6f76ce278f990b102cb3e19249f63c)
- New Module Pull Request
```paste below
```
> [stable-1] Update GHAs

- .github/workflows/ansible-test.yml
- .github/workflows/extra-tests.yml
Spread out nightly CI run times a bit.
CI
> Schedule nightly CI at 5:15

- .github/workflows/ansible-test.yml
Backport of #79 to stable-1.
CI
> [stable-1] Bump codecov action

- tests/ee/roles/smoke/tasks/main.yml
ansible.netcommon 3.0.0 was released, which changed the content of an error message that the EE tests were looking for.
EE smoke tests
> Fix EE CI errors

- .github/workflows/ansible-test.yml
- tests/unit/plugins/modules/fake_api.py
- tests/unit/plugins/modules/test_api.py
- tests/unit/plugins/modules/test_api_facts.py
- tests/unit/requirements-stable-2.9.txt
- tests/unit/requirements.txt
Do not install library we do not use in the tests anyway.
Parts from #91.
CI
> Improve unit test performance

- .github/workflows/ansible-test.yml
> CI matrix: ansible-core's devel version supports Python 3.11

- changelogs/fragments/107-api-path-ip-dhcp-lease.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
- tests/unit/plugins/modules/fake_api.py
- tests/unit/plugins/modules/test_api_info.py
- tests/unit/plugins/modules/test_api_modify.py
Fixes second parts of #104.
api_modify
api_info
> Support absent values; support absent value 'all' for 'server' in 'ip dhcp-server lease'

- changelogs/fragments/123-api.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
api_modify, api_info - support API paths:
- ip route
- ip route vrf
- api_info
- api_modify
N/A
> Add support for ip route and ip route vrf

- tests/unit/plugins/modules/fake_api.py
- tests/unit/plugins/modules/test_api_info.py
- tests/unit/plugins/modules/test_api_modify.py
Test some of the new features.
api_info
api_modify
> Add more tests for api_info and api_modify

- changelogs/fragments/remove-unneeded-imports.yml
- plugins/cliconf/routeros.py
- plugins/module_utils/api.py
- plugins/modules/api.py
- plugins/modules/api_facts.py
- plugins/modules/command.py
- plugins/terminal/routeros.py
Prepare for https://github.com/ansible-collections/news-for-maintainers/issues/34.
various
> Remove unneccessary imports

- tests/sanity/extra/update-docs.py
- tests/unit/compat/builtins.py
- tests/unit/compat/mock.py
- tests/unit/compat/unittest.py
- tests/unit/plugins/module_utils/test__api_data.py
- tests/unit/plugins/modules/test_api.py
- tests/unit/plugins/modules/test_api_facts.py
- tests/unit/plugins/modules/test_api_find_and_modify.py
- tests/unit/plugins/modules/test_api_info.py
- tests/unit/plugins/modules/test_api_modify.py
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/34
tests
> Remove unnecessary test imports

- README.md
Continue yes/no → true/false translations.
various
> Normalize bools in documentation

- changelogs/fragments/158-ipv6_settings-disable.yml
- plugins/module_utils/_api_data.py
add support to disable ipv6 in API paths ``ipv6 settings``
ipv6 settings
> Add support to disable ipv6 in API paths ``ipv6 settings``

- changelogs/fragments/154-ip-dhcp-client-dhcp-options.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_modify.py
- tests/unit/plugins/modules/fake_api.py
- tests/unit/plugins/modules/test_api_modify.py
Fixes #148.
api_info
api_modify
> ip dhcp-client: dhcp-options can be removed with value ''

- tests/sanity/extra/update-docs.json
Make sure the test actually runs.
extra sanity tests
> Extra sanity tests: fix bad comma

- .github/workflows/ee.yml
- tests/ee/roles/smoke/tasks/main.yml
Similar to https://github.com/ansible-collections/community.crypto/pull/606.
EE tests
> Rewrite EE test workflow to use ansible-builder 3.0.0

- tests/integration/requirements.yml
- tests/requirements.yml
- tests/unit/requirements.yml
Backport of #173 to stable-1.
- Tes Pull Request
test requirements files
> [stable-1] Switch to Ansible Galaxy compatible requirements files for tests

- changelogs/fragments/200-add-routing-filter.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
RouterOS 7 added [route selections and filters](https://help.mikrotik.com/docs/display/ROS/Route+Selection+and+Filters).
> Add support for "routing filter {rule|select-rule}"

- changelogs/fragments/201-add-user-settings.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
The `user settings` path contains settings related to passwords.
> Add support for "user settings"

- plugins/module_utils/_api_data.py
- tests/unit/plugins/modules/fake_api.py
- tests/unit/plugins/modules/test_api_info.py
- tests/unit/plugins/modules/test_api_modify.py
> Allow to differ on API paths based on RouterOS version (2/2)

- changelogs/fragments/215-add-routing-table.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
`routing table` can be used for policy routing.
> Add support for "routing table"

- CHANGELOG.rst
- changelogs/changelog.yaml
Ref: https://github.com/ansible/ansible-documentation/issues/455
changelog
> Fix typo in changelog

- changelogs/fragments/223-add-ip-dhcp-server-option.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Make it possible to manage IPv4 DHCP server options.
> Add support for the "ip dhcp-server option" path

- changelogs/fragments/224-add-port-remote-access.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Add support for the "port remote-access" path.
> Add support for the "port remote-access" path

- changelogs/fragments/220-routing-id-bgp-connection.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
This PR adds support for `routing id` and `routing bgp connection`.
Neither of these appear to have primary keys, the router accepts duplicates.
* `api_info`
* `api_modify`
Note that `routing bgp connection` has a lot more options than I've included in this PR.
<details>
<summary>For example on my ROS 7.10 device</summary>
```
/routing/bgp/connection> add
add-path-out --
address-families --
as --
cisco-vpls-nlri-len-fmt --
cluster-id --
comment -- Short description of the item
connect --
copy-from -- Item number
disabled -- Defines whether item is ignored or used
hold-time --
input.accept-communities --
input.accept-ext-communities --
input.accept-large-communities --
input.accept-nlri --
input.accept-unknown --
input.affinity --
input.allow-as --
input.filter -- …
```
> Support routing id and bgp connection

- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Ref: https://github.com/ansible-collections/community.routeros/pull/226#discussion_r1412878986
API data
> API data: allow to declare some versions as unsupported, and to provide an explicit message

- changelogs/fragments/239-wireless-tx-power.yml
- plugins/module_utils/_api_data.py
Add support for the "tx-power" wireless parameter.
> Add support for the "tx-power" wireless parameter

- changelogs/fragments/245-add-radius-path.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Fixes #241 - add "radius" path.
- api_info
- api_modify
None.
> Add the 'radius' path

- .github/workflows/extra-tests.yml
- .github/workflows/import-galaxy.yml
Backport of #249 to stable-1.
CI
> [stable-1] Use import galaxy workflow from ansible-collections/community.docker#754

- changelogs/fragments/263-sys-pkg-update.yml
- plugins/module_utils/_api_data.py
Add missing fields in "system package update".
> Add missing fields in "system package update"

- changelogs/fragments/286-add_ppp_secret_path.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Add support for 'ppp secret' path
- api_info
- api_modify
> Add support for 'ppp secret' path

- changelogs/fragments/294-add-system-health-settings-path.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Add configuration path `system health settings`.
- api_info
- api_modify
> Add `system health settings` path

- changelogs/fragments/295-add_system_resource_irq_rps_path.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Support API path `/system resource irq rps`
- api_info
- api_modify
> Add support for `/system resource irq rps` path

- changelogs/fragments/300-add-ip-dhcp-server-matcher.yml
- changelogs/fragments/300-set-ip-dhcp-option-force-default.yml
- changelogs/fragments/302-ospf-static-neighbor.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Upstream documentation:
https://help.mikrotik.com/docs/display/ROS/OSPF#OSPF-StaticNeighbourconfiguration
> Add support for the "routing ospf static-neighbor" path

- changelogs/fragments/303-add-ipv6-nd-prefix.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Upstream documentation:
https://help.mikrotik.com/docs/display/ROS/IPv6+Neighbor+Discovery#IPv6NeighborDiscovery-Prefix
> Add support for the "ipv6 nd prefix" path

- changelogs/fragments/309-add-igmp-proxy.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Upstream documentation:
https://help.mikrotik.com/docs/display/ROS/IGMP+Proxy
> Add support for the "routing igmp-proxy" path

- changelogs/fragments/310-add-ip-dns-adlist.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Upstream documentation:
https://help.mikrotik.com/docs/display/ROS/DNS#DNS-Adlist
> Add support for the "ip dns adlist" path

- changelogs/fragments/313-add-routing-filter-num-list.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Added `routing filter num-list` support, similar as `routing filter rules`
- New Module Pull Request
```paste below
```
> Added support for 'routing filter num-list'

- changelogs/fragments/331-add-routing-filter-community-list.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
added community-list for (routing filter)
> community-list for /routing/filter

- .github/workflows/ee.yml
- .github/workflows/extra-tests.yml
- .github/workflows/reuse.yml
Fix some issues in GHA workflows pointed out by zizmor (https://github.com/woodruffw/zizmor).
CI
> CI: Fix some issues pointed out by zizmor

- plugins/cliconf/routeros.py
- plugins/doc_fragments/api.py
- plugins/doc_fragments/attributes.py
- plugins/modules/api.py
- plugins/modules/api_facts.py
- plugins/modules/api_find_and_modify.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
- plugins/modules/command.py
- plugins/modules/facts.py
- update-docs.py
Reformat the YAML documentation embedded into Python files with [andebox](https://pypi.org/project/andebox/).
various
> Reformat documentation with 'andebox yaml-doc'

- changelogs/fragments/343-add-ip-dns-forwarders.yml
- plugins/module_utils/_api_data.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
Added `ip dns forwarders` support
- New Module Pull Request
```paste below
```
> Added support for 'ip dns forwarders'

- changelogs/fragments/345-interface-wifi-provisioning.yml
- plugins/module_utils/_api_data.py
> interface wifi provisioning: remove primary key

- tests/integration/targets/filter_quoting/tasks/main.yml
- tests/unit/plugins/modules/test_api.py
- tests/unit/plugins/modules/test_api_facts.py
- tests/unit/plugins/modules/test_api_find_and_modify.py
- tests/unit/plugins/modules/test_api_info.py
- tests/unit/plugins/modules/test_api_modify.py
- tests/unit/plugins/modules/test_command.py
- tests/unit/plugins/modules/test_facts.py
- tests/unit/plugins/modules/utils.py
Move some parts from #346.
tests
> Improve tests

- changelogs/fragments/2.20.1.yml
- galaxy.yml
It's a potential maintenance burden, and nobody seems to expect anything for 2.x.y anymore.
changelog
> Declare 2.x.y EOL

- tests/ee/roles/filter_quoting/tasks/main.yml
EE tests with devel currently fail.
EE tests
> Adjust EE tests

- .github/workflows/docs-pr.yml
- .github/workflows/docs-push.yml
- .github/workflows/ee.yml
- .gitignore
- .yamllint
- .yamllint-docs
- .yamllint-examples
- antsibull-nox.toml
- galaxy.yml
- plugins/filter/join.yml
- plugins/filter/list_to_dict.yml
- plugins/filter/quote_argument.yml
- plugins/filter/quote_argument_value.yml
- plugins/filter/split.yml
- plugins/modules/api.py
- plugins/modules/api_facts.py
- plugins/modules/api_find_and_modify.py
- plugins/modules/api_info.py
- plugins/modules/api_modify.py
- plugins/modules/command.py
- plugins/modules/facts.py
- tests/integration/requirements.yml
Uses antsibull-nox to run yamllint both for YAML files and YAML content in plugin docs.
CI
> Add YAML linting to CI, and reformat YAML files and content

- changelogs/fragments/373-api_find_and_modify-dynamic-builtin.yml
- plugins/modules/api_find_and_modify.py
- tests/unit/plugins/modules/test_api_find_and_modify.py
Fixes #372.
api_find_and_modify
> api_find_and_modify: allow to ignore dynamic and builtin entries

- changelogs/fragments/398-api-id.yml
- plugins/modules/api.py
> api: allow querying for vlan-ids

- changelogs/fragments/406-fix.yml
- plugins/modules/command.py
Follow-up to #405. Fix string_types replacement.
various
> Fix string_types replacement.
