ansible-collections/community.routeros

changelogs/fragments/3-api-ssl.yml
plugins/modules/api.py

The problem is that the function parameter is called `ssl`, which hides the `ssl` module which is also used in that function. This results in `error: 'bool' object has no attribute 'create_default_context'`.
api

Fix crash when ssl parameter of api is used

---

changelogs/fragments/community.network-138-routeros-allow-slash.yml
plugins/terminal/routeros.py

Backport of ansible-collections/community.network#138.

Allow `/` in hostnames/identity strings in terminal prompt parsing

---

README.md
galaxy.yml

The docs on the Ansible docsite will only appear once this collection is included in 2.10.x. This PR adds docs links to [my docsite](https://ansible.fontein.de/) which should be adjusted once the Ansible docsite contains community.routeros.
@heuels @NikolayDachev is this ok for you?
collection

Add preliminary documentation links

---

changelogs/fragments/13-remove-id-restriction-for-api.yaml
plugins/modules/api.py

Remove .id restriction, we have separate checks already (where is needed)
Fixes #13
community.routeros.api

remove .id restriction for list_to_dic

---

README.md

This PR adds a note to README about router identity name conventions that should be followed, and a note about nested commands being unsupported.
—

docs: add note about hostnames and nested commands

---

changelogs/fragments/18-support-dashes-in-username.yml
plugins/terminal/routeros.py

Fixes #17.
`community.routeros.command`, `community.routeros.facts`
```paste below
```

feat: support dashes in username

---

.github/workflows/ansible-test.yml

ansible/galaxy#2429 is getting to a point where it is a huge PITA. To work around it, we directly clone the corresponding git repositories.
CI

CI: Stop using ansible-galaxy collection install to install a collection

---

changelogs/fragments/34-api-ciphers.yml
plugins/modules/api.py

Old ciphers shouldn't be used. Devices that use newer ciphers couldn't be reached as the cipher was locked to sslv3.

Disable use of deprecated Ciphers

---

docs/docsite/extra-docs.yml
docs/docsite/rst/api-guide.rst
docs/docsite/rst/ssh-guide.rst

This adds two scenario guides using the extra docs feature. Once this is included in the next Ansible release, this will show up on https://docs.ansible.com/ansible/latest/collections/community/routeros/ !
Right now, you can look at the result of this PR at https://ansible.fontein.de/collections/community/routeros/index.html#plugins-in-community-routeros (note the two links under `Guides`):
- https://ansible.fontein.de/collections/community/routeros/docsite/api-guide.html
- https://ansible.fontein.de/collections/community/routeros/docsite/ssh-guide.html
docs

Add basic scenario guides

---

changelogs/fragments/ansible-core-_text.yml
plugins/cliconf/routeros.py
plugins/module_utils/routeros.py
plugins/modules/api.py
plugins/terminal/routeros.py
tests/unit/plugins/modules/utils.py

While the private API `ansible.module_utils._text` was the default place to get `to_text`, `to_bytes` and `to_native` for a long time, at least since Ansible 2.9 there's a non-private alternative: `ansible.module_utils.common.text.converters`. So let's use it :)
various plugins

Replace ansible.module_utils._text by ansible.module_utils.common.text.converters

---

README.md
changelogs/fragments/37-api-validate-cert-options.yml
docs/docsite/rst/api-guide.rst
plugins/modules/api.py

Follow-up to https://github.com/ansible-collections/community.routeros/pull/34#discussion_r649076021.
This adds three options:
- `validate_certs` (default value `true`);
- `validate_cert_hostname` (default value `false`, for backwards compatibility);
- `ca_path` (same name as similar option in ansible/ansible#71979).
api

Add options to control certificate validation for api module

---

README.md
galaxy.yml

The `devel` docs (https://docs.ansible.com/ansible/devel/collections/community/routeros/) are (usually) regenerated nightly and contain the latest releases of a collection. We should point to the devel docs as our main documentation location.
(It will also show the 2.0.0 docs if we release 2.0.0, even though the `latest` docs will stick to the latest release included in Ansible 4.x.y.)
README.md
galaxy.yml

Adjust docs links to devel docs

---

changelogs/fragments/39-api-fail.yml
plugins/modules/api.py
tests/unit/plugins/modules/test_api.py

Right now, the module will not fail when `return_result` is called with `status=False`, since it looks for `status == 'False'` (string instead of boolean).
api

Allow api module to fail

---

changelogs/fragments/43-sanity.yml
plugins/cliconf/routeros.py
tests/unit/plugins/modules/test_facts.py

ansible-test's pylint in devel has been upgraded to a new version. Fixes new sanity errors it reports.
various

Fix sanity failures

---

changelogs/fragments/47-api-split.yml
plugins/modules/api.py

While reviewing #45 I noticed that there are two `split()` calls which need a split limit.
I rewrote the one handling `WHERE` to work better with #45 (namely first do the splitting, then search for the token `WHERE` in the splitted list to avoid finding a `WHERE` in a quoted string), and added a limit to the other.
api

api: improve split handling

---

changelogs/fragments/45-api-split.yml
plugins/modules/api.py
tests/unit/plugins/modules/test_api.py

Closes https://github.com/ansible-collections/community.routeros/issues/44
`routeros_api`

fix(api): fixed a bug when splitting the argument string

---

.github/workflows/ee.yml
changelogs/fragments/83-ee.yml
meta/ee-requirements.txt
meta/execution-environment.yml
tests/ee/all.yml
tests/ee/roles/filter_quoting/aliases
tests/ee/roles/filter_quoting/tasks/main.yml
tests/ee/roles/smoke/tasks/main.yml

Try to make this collection EE ready, with tests. Similar to https://github.com/ansible-collections/community.dns/pull/93.
collection

Make EE ready

---

plugins/filter/join.yml
plugins/filter/list_to_dict.yml
plugins/filter/quote_argument.yml
plugins/filter/quote_argument_value.yml
plugins/filter/split.yml
tests/sanity/extra/no-unwanted-files.py

Add filter documentation using the new sidecar docs feature for ansible-core 2.13. Rendered with https://github.com/ansible-community/antsibull-docs/pull/6 to: https://ansible.fontein.de/collections/community/routeros/index.html#filter-plugins
filter plugin documentation

Add filter documentation

---

changelogs/fragments/89-quoting.yml
plugins/module_utils/quoting.py
tests/ee/roles/filter_quoting/tasks/main.yml
tests/integration/targets/filter_quoting/tasks/main.yml
tests/unit/plugins/module_utils/test_quoting.py

`\_` means a quoted space, not a quoted underscore.
(un)quoting filters
api module

Handle escape sequence \_ correctly

---

changelogs/fragments/90-api-action-group.yml
docs/docsite/rst/api-guide.rst
meta/runtime.yml

This allows to globally specify parameters for all `api*` modules.
This includes #88 and I will rebase once that one is merged. Then this should be ready for review. Basically only the last commit is relevant.
meta/runtime.yml
docs

Add community.routeros.api module defaults group

---

changelogs/fragments/63-add-extended_query.yml
plugins/modules/api.py
tests/unit/plugins/modules/fake_api.py
tests/unit/plugins/modules/test_api.py

Right now community.routeros.api query - WHERE is limited to single criteria.
We should update it to use all librouteos functionality. Also this will help with routeros/ansible idempotent functionality.
For understandable reasons RouterOS allow to add multiple configs with same value (for some configurations), in result when we add something with API we are not able to do correct match if the required config already exist or not which will make duplicated config entries!.
For example 'add' task can be executed only if 'query' do not return .id for existing config which match multiple criteria. etc.
community.routeros.api
libouteros: https://github.com/luqasz/librouteros
librouteros docs: https://librouteros.readthedocs.io/en/latest/query.html#
What we missing is …

update community.routeros.api query functionality 

---

changelogs/fragments/95-api-encoding.yml
plugins/doc_fragments/api.py
plugins/module_utils/api.py
plugins/modules/api.py
plugins/modules/api_find_and_modify.py

Fixes one of the issues mentioned in https://github.com/ansible-collections/community.routeros/pull/91#issuecomment-1134860696. Note that `encoding='UTF-8'` doesn't properly work without https://github.com/luqasz/librouteros/pull/131.
API modules

Add encoding option to API modules

---

.github/workflows/ansible-test.yml

ansible-core devel will drop support for Python 3.8 on controller soon (see https://github.com/ansible-collections/news-for-maintainers/issues/18).
CI

Improve CI

---

changelogs/fragments/109-add-timeout-parameter-to-api.yml
plugins/doc_fragments/api.py
plugins/module_utils/api.py

At the moment the timeout of librouteros is by default 10 seconds. For some tasks this is to short.
librouteros already provides an option to overwrite the timeout. This commit add the parameter to this module.
Only affects the api part of the module. Added timeout parameter.
Sorry don't know how the create the `verbatim` output.

Added timeout setting for api.

---

changelogs/fragments/command-check_mode.yml
docs/docsite/rst/api-guide.rst
meta/runtime.yml
plugins/doc_fragments/attributes.py
plugins/modules/api.py
plugins/modules/api_facts.py
plugins/modules/api_find_and_modify.py
plugins/modules/api_info.py
plugins/modules/api_modify.py
plugins/modules/command.py
plugins/modules/facts.py

Uses attributes to document module capabilities.
This PR also adds a warning to the command module (and into the changelog) that the module claims to support check mode, but it shouldn't and that this will change in community.routeros 3.0.0.
all

Use attributes to document module capabilities; warn about command module's check_mode support

---

changelogs/fragments/119-api.yml
changelogs/fragments/120-api.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

api_modify, api_info - support API paths:
-  ``interface list``
- ``interface list member``
api_info
api_modify
N/A

Interface list

---

README.md
changelogs/fragments/124-api.yml
docs/docsite/rst/api-guide.rst
plugins/doc_fragments/api.py
plugins/module_utils/api.py

Add new option to the api
```
force_no_cert: false
```
Connect to a router without a certificate by using ADH ciphers. This can be useful when setting up a device.
- api_*
When enabling the api-ssl service on RouterOS devices it does not have a certificate, but allows to connect to the device by using the anonymous Diffie-Hellman (ADH) ciphers. This can help during the initial setup.

Add new api option force_no_cert

---

changelogs/fragments/134-command-safemode.yml
plugins/terminal/routeros.py

Updating the regex that matches the terminal prompt for ``command`` module in safe mode. 
command
Commands are timing out in safe mode now, because the module will never match the terminal prompt which is required in order to recognize the end of the command output. 
In order to try the functionality, ``CTRL + X`` (``\x18``) has to be passed as a command to the module.

terminal regex udpate to match the terminal prompt in safe mode

---

changelogs/fragments/143-add-wireguard.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

Adds support for configuring wireguard interfaces and peers.
* api_modify
* api_info
Missing tests and equally as important, `interface wireguard` editing doesn't behave as expected (misconfiguration error, see below). The API obfuscates the value of `private-key` so the diff is broken, for example:
```
--- before
+++ after
@@ -6,7 +6,7 @@
"listen-port": 13231,
"mtu": 1420,
"name": "WG1",
-            "private-key": "*****"
+            "private-key": "mLh5K+/uJmZJ1zqarPYh0OyBaCgI1n+xAUBvsPBC+3I="
}
]
}
```
This happens even if that private key is already configured on the router. I was unable to find documentation on how to get the API to return sensitive information like this.
UPDATE: This is fixed by adding the "sensitive" policy to the group used to connect.
``` …
```

Add wireguard interface and peers

---

changelogs/fragments/142-dns-regexp.yml
plugins/module_utils/_api_data.py
plugins/modules/api_modify.py
tests/unit/plugins/module_utils/test__api_data.py
tests/unit/plugins/modules/test_api_modify.py

Fixes #141 
* api_modify
* api_info
I've also changed the `test_invalid_required_missing` to use "ip dhcp-server" instead.
Since for "ip dns static", one of "name" or "regexp" is required (but not both), I've added a new `require_one_of` attribute to APIData and associated tests. Please let me know if this design doesn't fit with the rest of the code.

Add regexp field to ip dns static

---

changelogs/fragments/153-ip_firewall_layer7-protocol.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

Add support for API paths   "ip firewall layer7-protocol"
ip firewall layer7-protocol
```

Add support for "ip firewall layer7-protocol"

---

changelogs/fragments/156-ip_dhcp-server_network.yml
plugins/module_utils/_api_data.py

Adapt data for API paths "ip dhcp-server network"
Bug solved: when a next-server is configured, it's impossible to remove it.  
- When trying with `''` : `invalid value for argument next-server`
- When trying with `None` : `Key \"next-server\" must not be disabled (value null/~/None)`
ip dhcp-server network

Correction and Bugfix for ip dhcp-server network

---

plugins/modules/api.py
tests/sanity/extra/extra-docs.json
tests/sanity/extra/extra-docs.py

Use `antsibull-docs lint-collection-docs --plugin-docs` to do additional documentation validation. This is important if the docs build workflow is no longer there (#6344).
This also ensures that no semantic markup is used. This should be changed once the last Ansible 6.x.y release is out containing this collection; from then on we can (relatively) safely start using semantic markup without defacing the Ansible 7 (or before) documentation.
CI

Do extra docs validation; explicitly disallow semantic markup in docs

---

changelogs/fragments/177-facts-parsing.yml
plugins/modules/facts.py

facts: fix bug in preprocessing when wrapped line is appended to a non-existing entry

---

changelogs/fragments/180-fix-tls-in-tool-email.yml
plugins/module_utils/_api_data.py

Fixes #179: Add missing /tool/e-mail parameter "tls"
In the
[documentation](https://help.mikrotik.com/docs/display/ROS/E-mail#Email-Properties) the parameter "tls" is mentioned but it cannot be used. The old "start-tls" parameter is not mentioned there (only on the [old documentation](https://wiki.mikrotik.com/wiki/Manual:Tools/email#Properties)). Trying to use the paramter "tls" lead to the erro message `FAILED! => {"changed": false, "msg": "Unknown key \"tls\"."}`.
community.routeros.api_modify
None.

Fixes #179: Add missing /tool/e-mail parameter "tls"

---

.github/workflows/ansible-test.yml
.github/workflows/extra-tests.yml
.github/workflows/import-galaxy.yml

Bump hard-coded Python versions in workflows from 3.10 to 3.11.
Also drop Python 3.9 run for devel.
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/48
CI

CI: Bump hard-coded Python versions to 3.11; drop Python 3.9 with devel

---

changelogs/fragments/180-fix-engine-id-suffix-in-snmp.yml
plugins/module_utils/_api_data.py

Fixes #189: Add missing /snmp parameter "engine-id-suffix"
In the [documentation](https://help.mikrotik.com/docs/display/ROS/SNMP#SNMP-GeneralProperties) it is not (yet) updated but at least on version 7.10 it is already changed.
community.routeros.api_modify
None

Fixes #189: Add missing /snmp parameter "engine-id-suffix"

---

changelogs/fragments/192-add-ip_traffic-flow_target-path.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

Adding the path **ip traffic-flow target** with the default values I could find.
- api_info
- api_modify
None.

Fixes #191: Add path 'ip traffic-flow target'

---

changelogs/fragments/197-dns-static-addrlist-matchsubdomain.yml
plugins/module_utils/_api_data.py
tests/unit/plugins/modules/test_api_find_and_modify.py
tests/unit/plugins/modules/test_api_modify.py

RouterOS 7.5 added `address-list` and `match-subdomain` as fields for static DNS records ([changelog](https://forum.mikrotik.com/viewtopic.php?t=188851)).

Support "address-list" and "match-subdomain" in static DNS records

---

changelogs/fragments/198-ip-nd-mode.yml
plugins/module_utils/_api_data.py

RouterOS 7.7 added a `mode` parameter to the IPv4 neighbor discovery configuration ([changelog](https://forum.mikrotik.com/viewtopic.php?t=192427)).

Support "mode" in IPv4 neighbor discovery configuration

---

plugins/module_utils/_api_data.py

Commit 2164261 from #199 added support for `interface ppp-client`. It missed the `apn` property and added the runtime-only `running` property.
No changelog fragment is included as this is a pre-release bugfix.

Add "apn", remove "running" property for ppp-client interfaces

---

changelogs/fragments/205-add-iot-modbus.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

The default values match those of RouterOS 7.11 on a Mikrotik RB924i-2nD-BT5&BG77 ("Knot").
[Upstream documentation](https://help.mikrotik.com/docs/pages/viewpage.action?pageId=61046813).

Add support for "iot modbus"

---

changelogs/fragments/210-date-time-gmt-offset.yml
plugins/module_utils/_api_data.py

These properties are necessary to read and set the time as seen by RouterOS.

Support "date", "time" and "gmt-offset" in "system clock"

---

changelogs/fragments/213-read-write-only.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py
tests/unit/plugins/module_utils/test__api_data.py
tests/unit/plugins/modules/fake_api.py

Ref: https://github.com/ansible-collections/community.routeros/pull/211/files#r1313462457
CC @hansmi - I didn't really have time to test this yet, but if you already want to try it out: enjoy ;-)
API data
api_info
api_modify

Implement basic support for read-only and write-only keys in api_info and api_modify

---

plugins/module_utils/_api_data.py

Commit 4b09951 added code looking for a non-existent `fully_supported` attribute.

Fix for "'VersionedAPIData' object has no attribute 'fully_supported'"

---

changelogs/fragments/211-user.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

Make it possible to manage users via the `user` path.

Add support for the "user" path

---

changelogs/fragments/218-snmp-engine-id.yml
plugins/module_utils/_api_data.py

Fixes #208.
CC @phox142 @derdeagle (#217) - PTAL!
API data

Fix snmp path's engine-id/engine-id-suffix for ROS 7.10+

---

changelogs/fragments/233-wireless-running-read-only.yml
plugins/module_utils/_api_data.py

Commit e4a21311 added API data for the "interface wireless" path. It contained the read-only "running" parameter. Writing to the parameter fails:
```
Error while modifying for name="…" (ID *3): unknown parameter running
```

Make wireless parameter "running" read-only

---

changelogs/fragments/235-add-missing-dns-attributes.yml
plugins/module_utils/_api_data.py

- doh-max-concurrent-queries
- doh-max-server-connections
- doh-timeout
The parameters mentioned above seem to be added in version 7.8 as far as I could tell from the changelogs.
- api_info
- api_modify

Fixes #230: Add missing DoH parameters in the "ip dns" path

---

changelogs/fragments/246-add-routing-rule-path.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

Add the `routing rule` path for #162 .
In the issue the path `routing table` was requested but this was added with PR #215 . Somewhere in the depths of the MikroTik documentation I read that `routing table` would only make limited sense without `routing rule` but I cannot find it anymore.
- api_info
- api_modify
None.

Add 'routing rule' path

---

changelogs/fragments/247-removed-primary-key-host-in-tool-netwatch.yml
plugins/module_utils/_api_data.py

I've changed the primary key for `tool netwatch` from `name` to `host`, because `name` isn't used at all.
When adding `name` to the playbook:
```
TASK [common : (routeros) Set netwatch] *********************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'name'
fatal: [routeroshostname -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/username/.ansible/tmp/ansible-tmp-1704395855.7240071-1606677-122124317821788/AnsiballZ_api_modify.py\", line 107, in <module>\n    _ansiballz_main()\n  File …
```

Changed primary key of 'tool netwatch'

---

changelogs/fragments/257-make-user_group-modifiable.yml
plugins/module_utils/_api_data.py

Fixes #256: make path `user group` modifiable and add `comment` attribute
- api_info
- api_modify

Fixes #256: make path `user group` modifiable and add `comment` attribute

---

changelogs/fragments/259-add-routeros7-support-for-ip-vrf.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

```paste below
In router OS 7, the path to vrf and the fields used have changed
tested on v7.13.3
```

Change ip vrf for router OS v7

---

changelogs/fragments/262-fix-date-removal.yml
plugins/modules/facts.py

As in newer versions of RouterOS the date format in the export is 2024-10-02 and no longer 2024/10/02, the regex to remove timestamps did no longer match all cases. This is fixed here.
Documentation says that, the ansible_net_config_nonverbose fact is idempotent in the sense that if the facts module is run twice and the device’s config was not changed between the runs, the value is identical. This is achieved by running /export and stripping the timestamp from the comment in the first line.
facts
Date was successfully removed from export in RouterOS 7.9.* but not in 7.12.*

Fix date removal in nonverbose config

---

changelogs/fragments/264-wireless-running-default.yml
plugins/module_utils/_api_data.py

The `running` field can't be configured. By having a default value it's written and shows up in diffs.

Remove default value for "running" field in "interface wireless"

---

plugins/module_utils/_api_data.py
tests/unit/plugins/module_utils/test__api_data.py

Ref: https://github.com/ansible-collections/community.routeros/pull/264#issuecomment-1975073650
_api_data.py

KeyInfo: prevent read_only usage with can_disable, remove_value, absent_value, default, or required

---

tests/sanity/ignore-2.17.txt
tests/unit/compat/mock.py

Fixes nightly CI: https://github.com/ansible-collections/community.routeros/actions/runs/8399659133/job/23006035379
tests/unit/compat/mock.py

Ignore pylint warnings for construct that does not work with Python 2

---

changelogs/fragments/270_fix_ipv6_from_pool_default_value.yml
plugins/module_utils/_api_data.py

When not set, the RouterOS API always returns the IPv6 Address 'from-pool' value as '', however _api_data.py has no default value set.
This PR fixes this issue.
Test task:
```
tasks:
- name: Add IPv6 address with defaults
community.routeros.api_modify:
path: ipv6 address
handle_absent_entries: remove
handle_entries_content: remove
data:
- address: fedc:1234:5678:abcd::1/64
interface: ether1
```
Output from api_info:
```
TASK [Print output of queue_simple_api_info] **************************************************************************************************************************************
ok: [testrtr1] => {
"queue_simple_api_info": {
"changed": false,
"failed": false,
"result": [
{
"!comment": null,
".id": "*9",
"address": "fedc:1234:5678:abcd::1/64", …
```

Fix IPv6 address 'from-pool' default value

---

changelogs/fragments/271-mpls_ldp_routeros_7_support.yml
plugins/module_utils/_api_data.py

RouterOS 7.1 completely re-writes the MPLS implementation (As per https://cdn.mikrotik.com/routeros/7.1/CHANGELOG), including support for multiple LDP instances.
This PR implements support for RouterOS 7.x LDP instances while retaining backwards compatibility with 6.x.
Some things to note:
- The 'vrf' value isn't required by the API, however as only one VRF is allowed per entry it seems sensible to consider this value s the primary key.
- As 'main' is the default VRF even when not defined, attempting to add an entry in the 'main' VRF while an entry with the VRF undefined is present will result in the error:
```Error while creating entry: failure: one active instance per VRF allowed```
- Whilst 'lsr-id' is able to be disabled, the router will not consider entries valid without it …

Add RouterOS 7.x support to '/mpls ldp' path

---

changelogs/fragments/273-add_interface_pppoe-server_support.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

Add support for '/interface pppoe-server server' path.
- api_info
- api_modify
Tested in RouterOS 6.49.10 and 7.14.2.
RouterOS 7.x supports two additional fields:
- accept-empty-service
- comment
Tasks used for testing:
**RouterOS 6.49.10**
```
tasks:
- name: Add interface pppoe-server server with defaults (RouterOS 6.x)
when: "'routeros6' in group_names"
community.routeros.api_modify:
path: interface pppoe-server server
handle_entries_content: remove
data:
- interface: ether1
- name: Add interface pppoe-server server with all values set (RouterOS 6.x)
when: "'routeros6' in group_names"
community.routeros.api_modify:
path: interface pppoe-server server
handle_entries_content: remove
data:
- interface: ether2
authentication: pap,chap
default-profile: …
```

Add support for '/interface pppoe-server server' path

---

.github/workflows/ee.yml

Apparently the pip is too old to be able to handle two requirements for netaddr (`netaddr` and `netaddr>=0.10.1`) in the same requirements.txt file...
See https://github.com/ansible-collections/community.routeros/actions/runs/9608694669/job/26503096454
EE CI

EE tests: stop building EE with RHEL UBI 8

---

changelogs/fragments/297-add-ip-ssh-host-key-type.yml
plugins/module_utils/_api_data.py

Add parameter `host-key-type` for the `ip ssh` path.
Fixes #280.
- api_info
- api_modify
None

Add parameter `host-key-type` for `ip ssh` path

---

changelogs/fragments/304-wireguard-name-responder.yml
plugins/module_utils/_api_data.py

From the RouterOS 7.15 changelog:
```
*) wireguard - added option to mark peer as responder only;
*) wireguard - added peer "name" field and display it in logs;
```

Support name and is-responder properties on Wireguard peers

---

changelogs/fragments/306-ingress-filtering-ros6.yml
plugins/module_utils/_api_data.py

The default only changed to `true` for ROS 7.
Ref: #125.
api_info
api_modify

api_info/api_modify: path /interface bridge [port]: fix default of ingress-filtering for ROS < 7

---

changelogs/fragments/311-add-defaults-fields-snmp-community.yml
plugins/module_utils/_api_data.py

Add missing default attribute to api_data
- snmp community

Add default to snmp community api_data

---

changelogs/fragments/321-dhcp-server-matcher-matching-type.yml
plugins/module_utils/_api_data.py

Support DHCP matching type added in RouterOS 7.16.

Support DHCP matching type added in RouterOS 7.16

---

changelogs/fragments/323-add-ros-7.16-parameters.yml
plugins/module_utils/_api_data.py

- `forward-reserved-addresses` with default value `False`
- `max-learned-entries` with default value `auto`
- `lldp-mac-phy-config` with default value `False` (from Router OS 7.15 release)
- `discover-interval` with default value `30s`
- `lldp-vlan-info` with default value `False`
- `ipv4-multipath-hash-policy` with default value `l3`
- `multipath-hash-policy` with default value `l3`
- `comment`
- `comment`
- `comment`
- `acccept-icmp-time-exceeded` with default value `False`
- `ttl` with defaut value `255`
- `max-sessions` with default value `20`

Add new parameters from RouterOS 7.16 release

---

changelogs/fragments/327-add-missing-ip-pool-fields.yml
plugins/module_utils/_api_data.py

add missing fields `comment`, `copy-from`, `next-pool` to `ip pool` path.
Not sure in what version if routeros they were introduced, the oldest I have access to is 6.46 and they are present there.
`api_info`
`api_modify`
`ip pool`
```paste below
```

fix: add missing fields to `ip pool` path

---

plugins/doc_fragments/attributes.py
plugins/modules/api.py
plugins/modules/api_facts.py
plugins/modules/api_find_and_modify.py
plugins/modules/api_info.py
plugins/modules/api_modify.py
plugins/modules/command.py
plugins/modules/facts.py

Adds a new attribute `idempotent` for module documentation, which states whether (resp. under which circumstances) the module is idempotent.
Related PRs:
- https://github.com/ansible-collections/community.dns/pull/238
- https://github.com/ansible-collections/community.crypto/pull/833
- https://github.com/ansible-collections/community.docker/pull/1022
- https://github.com/ansible-collections/community.hrobot/pull/132
- https://github.com/ansible-collections/community.sops/pull/217
module documentation

Add 'idempotent' attribute

---

changelogs/fragments/339-add-require-message-auth-for-radius.yml
plugins/module_utils/_api_data.py

Fixes #338 by adding the attribute "require-message-auth" (which was added in RouterOS version 7.15) to the "radius" path.
- _api_data.py

Fixes #338: Add require-message-auth in radius path

---

changelogs/fragments/341-add-dhcpv6-client-use-interface-duid.yml
plugins/module_utils/_api_data.py

api_info, api_modify: add the ``use-interface-duid`` option for DHCPv6 client. 
api_info, api_modify
This option prevents issues with Fritzbox modems and routers, when using virtual interfaces (like VLANs) may create duplicated records in hosts config, this breaks original "expose-host" function.
The ``use-interface-duid`` corrects this behavior: the DUID for link-local address and DHCPv6 request are the same, and user can configure per-host option in Fritzbox OS as expected.
Tested on current ``7.17`` and ``7.16.2`` versions:
```diff
--- before
+++ after
@@ -12,6 +12,7 @@
"pool-prefix-length": 64,
"prefix-hint": "::/59",
"request": "address,prefix",
+            "use-interface-duid": true,
"use-peer-dns": false
}
]
```

DHCPv6 client: add missing 'use-interface-duid' option

---

changelogs/fragments/342-add-interface-6to4.yml
plugins/module_utils/_api_data.py
plugins/modules/api_info.py
plugins/modules/api_modify.py

Add 'interface 6to4' path, allows manage 6to4 tunnels like HE
- api_info, api_modify
Add the ``interface 6to4`` path. 
Used to manage ipv6 tunnels via tunnel-brokers like HE, where native ipv6 is not provided.
[Mikrotik documentation related to 6to4](https://help.mikrotik.com/docs/spaces/ROS/pages/135004174/6to4)

Add 'interface 6to4' path, allows manage 6to4 tunnels like HE

---

changelogs/fragments/350-ip-cloud-ddns-enabled-auto.yml
plugins/module_utils/_api_data.py

From the RouterOS 7.17 changelog:
> *) cloud - changed ddns-enabled setting from "no" to "auto" (service
> is enabled when BTH is enabled);
`no` is not supported anymore, only `yes` and `auto` are.

Change default for ddns-enabled to "auto" for RouterOS 7.17 and newer

---

changelogs/fragments/358-mdns-repeat-ifaces.yml
plugins/module_utils/_api_data.py

RouterOS 7.16 introduced an mDNS proxy, configurable via `mdns-repeat-ifaces` under `/ip/dns`.

Add "mdns-repeat-ifaces" field to "ip dns"

---

changelogs/fragments/360-bgp-connection-afi.yml
plugins/module_utils/_api_data.py

Field name change in 'routing bgp connection' (from 'address-families' to 'afi')
```paste below
```

Field name change in 'routing bgp connection' (from 'address-families' to 'afi')

---

changelogs/fragments/364-wireguard-responder.yml
plugins/module_utils/_api_data.py

RouterOS 7.17 renamed the `is-responder` property in `/interface/wireguard/peers` to `responder`.

Rename Wireguard peer "is-responder" to "responder" for RouterOS 7.17

---

changelogs/fragments/382-mangle-passthrough.yml
plugins/module_utils/_api_data.py

The behaviour of the `passthrough` property in `ip/firewall/mangle` has changed in RouterOS 7.19:
```
*) firewall - always show "passthrough" when exporting mangle table;
```
Per the documentation at [1] the default is `true`.
[1] https://help.mikrotik.com/docs/spaces/ROS/pages/48660587/Mangle

Set mangle passthrough default for RouterOS 7.19

---

changelogs/fragments/381-logging-cef.yml
plugins/module_utils/_api_data.py

Add fields to /system/logging/action to support new CEF related fields
From ROS 7.18 changelogs:
*) log - added CEF format support for remote logging;
*) log - added option to select TCP or UDP for remote logging;

Update logging action fields for ROS 7.18

---

changelogs/fragments/394-iface-list-defaults.yml
plugins/module_utils/_api_data.py
tests/unit/plugins/modules/test_api_info.py

Without a default value a pre-existing value isn't removed unless the caller specifies the property.

Set default value for interface list include/exclude

---

changelogs/fragments/391-report-unknown-interfaces.yml
plugins/modules/api_facts.py

When an IP address had been configured on an interface that has since then disappeared (e.g. a tunnel interface was deleted) or was not discovered for other reasons, api_facts.py fails with KeyError because no pre-allocated dict is found under that interface name.
Note: missing interfaces on addresses are reported by the raw `.id` that previously identified the interface. The CLI represents this as `*id` (.e.g. `*23`), and in WinBox the interface name is shown as "unknown".
But issue #86 also reports cases where interfaces are not enumerated for other reasons despite them to exist.
This change collects these addresses nevertheless, leaving all interface properties undefined. For interfaces which RouterOS reports as unlinked, the device `"type": "unknown"` is also set, e.g.:
``` …
```

Handle IP addresses configured on disappeared interfaces

---

changelogs/fragments/401-vrf-logging.yml
plugins/module_utils/_api_data.py

From release [7.19.6](https://mikrotik.com/download/changelogs#c-stable-v7_19_6) it is now possible to set a VRF for the `system/logging/action`
('system', 'logging', 'action')
```
- name: remote
remote: 127.0.0.1
remote-log-format: syslog
remote-port: 514
remote-protocol: udp
src-address: 0.0.0.0
syslog-facility: daemon
syslog-severity: auto
syslog-time-format: bsd-syslog
target: remote
vrf: vrf_test
encoding: ASCII
ensure_order: false
force_no_cert: false
handle_absent_entries: remove
handle_entries_content: remove_as_much_as_possible
handle_read_only: error
handle_write_only: create_only
hostname: <redacted>
password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
path: system logging action
port: null
restrict: null
timeout: 10
tls: false
username: <redacted> …
```

Add support for VRF to API 'system/logging/action' from v7.19
